Repository Proyectos-Especiales-CCM/Cyber-Prepa-Front, pull requests merged in 2024-10, with the labels that each got.

#40 Login with Enter key done
  src/pages/Login/Login.tsx
Labels: feature

#44 Aceptar correos solamente con ID
  src/pages/Login/Login.tsx
  src/services/logInAccess/logInAccess.tsx
Labels: feature

#46 Enhance/improve cards
  src/components/AddStudentButton/AddStudentButton.tsx
  src/components/Card/Card.css
  src/components/Card/Card.tsx
  src/components/Card/initCountdown.ts
  src/components/CardExpander/CardExpander.css
  src/components/CardExpander/CardExpander.tsx
  src/components/EndPlayForAllButton/EndPlayForAllButton.tsx
Labels: enhancement, frontend

#48 Return 100 logs
  src/components/Tables/Logs/Logs.tsx
Labels: feature

#49 Login error feedback done
  src/pages/Login/Login.tsx
Labels: bug

#50 Icon to copy the student ID and use of copy package to implement clip…
  package.json
  src/components/CollapsedStudentItem/CollapsedStudentItem.tsx
  yarn.lock
Labels: feature

#52 Change game button
  src/components/CardExpander/CardExpander.css
  src/components/CardExpander/CardExpander.tsx
  src/components/ChangeGameButton/ChangeGameButton.tsx
  src/components/CollapsedStudentItem/CollapsedStudentItem.tsx
  src/components/CollapsedStudents/CollapsedStudents.tsx
  src/components/EndPlayButton/EndPlayButton.tsx
  src/components/Header/Header.tsx
  src/components/SanctionButton/SanctionButton.tsx
  src/components/Tables/Logs/Logs.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/routes/Router.tsx
  src/services/rental/patchPlayById.tsx
  src/store/gamesContext/gamesContext.tsx
  src/store/gamesContext/types.ts
  src/store/gamesContext/useGamesContext.tsx
  yarn.lock
Labels: enhancement
